restauracja/menu/urls.py
from django.urls import path
from .views import (
    CommentListView,
    CommentDetailView,
    CommentCreateView,
    CommentUpdateView,
    CommentDeleteView
)
from . import views

app_name = 'menu'
urlpatterns = [
    path('', views.index, name='places'),
    path('<int:place_id>/', CommentListView.as_view(), name='detail'),
    path('comment/<int:pk>/', CommentDetailView.as_view(), name='comment-detail'),
    path('comment/new/<int:place_id>', CommentCreateView.as_view(), name='comment-create'),
    path('comment/<int:pk>/update/', CommentUpdateView.as_view(), name='comment-update'),
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment-delete'),
    path('^<int:periodicMenu_id>/', views.dishes, name='dishes'),
]

restauracja/restauracja/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import include, path



urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls')),
    path('user/', include('users.urls')),
]

restauracja/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'
urlpatterns = [
    path('signup/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
]

restauracja/menu/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Place (models.Model):
    town = models.CharField(max_length=200)
    address = models.CharField(max_length=200)

    def __str__(self):
        return self.town

class Dishes(models.Model):
    name = models.CharField(max_length=200)                                              #nazwa
    description = models.CharField(max_length=500)                                                     #opis - z czego jest
    price = models.FloatField()                                                          #cena
    type = models.CharField(max_length=200)                                                            #Jaki typ potrawy

    def __str__(self):
        return self.name

class PeriodicMenu (models.Model):
    name = models.CharField(max_length=200, default="Menu przykładowe")
    period = models.CharField(max_length=200)                                       #Okres w jakim obowiązuje np. Zima
    dish = models.ManyToManyField(Dishes, blank=True, null=True)
    place = models.ManyToManyField(Place, null=True)

    def __str__(self):
        return self.name

class Comment (models.Model):
    comment_text = models.CharField(max_length=500)
    author = models.ForeignKey (User, on_delete=models.CASCADE)
    place = models.ForeignKey (Place, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.comment_text

    def get_absolute_url(self):
        return reverse('menu:detail', kwargs={'place_id': self.place.id})

restauracja/users/models.py
from django.db import models

# Create your models here.

restauracja/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

restauracja/menu/views.py
# Create your views here.

from django.http import HttpResponse
from django.shortcuts import get_object_or_404,render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from django.http import Http404
from django.template import loader

from .models import PeriodicMenu
from .models import Place
from .models import Comment
from .models import Dishes

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

def index(request):
    place_list = Place.objects.order_by('id')
    context = {'place_list': place_list}
    return render(request, 'menu/index.html', context)

# def detail(request, place_id):
#
#
#     menu_list = PeriodicMenu.objects.filter(place=place_id)
#     comments_list = Comment.objects.filter(place=place_id)
#
#     context = {'menu_list': menu_list,
#                'comments_list': comments_list
#                }
#
#     return render(request, 'menu/detail.html', context)

class CommentListView(ListView):
    model = Comment
    template_name = 'menu/detail.html'
    context_object_name = 'comments_list'
    ordering = ['timestamp']

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['menu_list'] = PeriodicMenu.objects.filter(place=self.kwargs.get('place_id'))
        context['comments_list'] = Comment.objects.filter(place=self.kwargs.get('place_id')).order_by('-timestamp')
        context['place'] = Place.objects.get(id=self.kwargs.get('place_id'))
        return context

class CommentDetailView(DetailView):
    model = Comment

class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['comment_text']

    def form_valid(self, form):
        form.instance.author = self.request.user
        place = Place.objects.get(id = self.kwargs.get('place_id'))
        form.instance.place = place
        return super().form_valid(form)

class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment
    fields = ['comment_text']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        comment = self.get_object()
        if self.request.user == comment.author:
            return True
        return False

class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment
    success_url = '/'

    def test_func(self):
        comment = self.get_object()
        if self.request.user == comment.author:
            return True
        return False



def dishes(request, periodicMenu_id):
    # try:
    #     menu = PeriodicMenu.objects.get(pk=periodicMenu_id)
    # except PeriodicMenu.DoesNotExist:
    #     raise Http404("Menu does not exist")
    # return render(request, 'menu/detail.html', {'menu':menu})
    menu = get_object_or_404(PeriodicMenu, pk=periodicMenu_id)
    return render(request, 'menu/dishes.html', {'menu': menu})

restauracja/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm

# Create your views here.


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! You are now able to log in!')
            return redirect('menu:places')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form':form})

@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST,
                                instance=request.user)
        if u_form.is_valid():
            u_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('users:profile')
    else:
        u_form = UserUpdateForm(instance=request.user)


    context = {
        'u_form': u_form
    }
    return render(request, 'users/profile.html', context)

restauracja/menu/templates/menu/base.html
<!DOCTYPE html>
<html lang="en">
<head>

     <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


   {% if title %}
        <title>Restaurant - {{ title }}</title>
    {% else %}
    <title>Restaurant</title>
    {% endif %}
</head>
<body>

    <div class = "container">
        {% block content %} {% endblock content %}
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

restauracja/menu/templates/menu/comment_confirm_delete.html
{% block content %}
    <div class = "content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class = "border-bottom mb-4">Delete Comment</legend>
                <h2>Are you sure you want to delete the post "{{ object.comment_text }}"</h2>
            </fieldset>
            <div class = "form-group">
                <button class = "btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a  class = "btn btn-outline-secondary" href="{% url 'menu:detail' object.place.id %}" >Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

restauracja/menu/templates/menu/comment_detail.html
{% block content %}
        <div class="article-metadata">
            <a class="mr-2" href="#">{{ object.author }}</a>
            <small class="text-muted">{{ object.timestamp|date:"F d, Y" }}</small>
        </div>
  <p >{{object.comment_text}}</p>
{%endblock content%}

restauracja/menu/templates/menu/comment_form.html
{% load crispy_forms_tags %}
{% block content %}
    <div class = "content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class = "border-bottom mb-4">Comment</legend>
                 {{ form|crispy }}
            </fieldset>
            <div class = "form-group">
                <button class = "btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}

restauracja/menu/templates/menu/detail.html
  <div class="navbar-nav">
        {% if user.is_authenticated %}
        <li> <a  href="{% url 'users:logout' %}">Log out</a></li>
        <li><a  href="{% url 'users:profile' %}">Profile</a></li>

        {%else%}
        <li><a  href="{% url 'users:login' %}">Log In</a></li>
        <li><a  href="{% url 'users:register' %}">Register</a></li>

        {% endif %}
  </div>

   {% if menu_list %}
    <ul>
    {% for menu in menu_list %}
        <li><a href="{% url 'menu:dishes' menu.id %}">{{ menu.name }}</a></li>
    {% endfor %}
    </ul>
    {% else %}
    <p>No menu are available. We are in the process of develop.</p>
    {% endif %}

{% block content %}
  <li><a href="{% url 'menu:comment-create' place.id %}">Create Comment</a>
  {% if comments_list %}
    {% for comment in comments_list %}
        <div class="article-metadata">
            <a class="mr-2" href="#">{{ comment.author }}</a>
            <small class="text-muted">{{ comment.timestamp|date:"F d, Y" }}</small>
            {% if comment.author == user %}
            <a class = "btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'menu:comment-update' comment.id  %}">Edit</a>
            <a class = "btn btn-danger btn-sm mt-1 mb-1" href="{% url 'menu:comment-delete' comment.id  %}">Delete</a>
            {% endif %}
        </div>
  <p >{{comment.comment_text}}</p>

    {% endfor %}
  {% else %}
  <p>No comments</p>
  {% endif %}
{%endblock content%}

restauracja/menu/templates/menu/dishes.html
<div class="navbar-nav">
        {% if user.is_authenticated %}
        <li> <a  href="{% url 'users:logout' %}">Log out</a></li>
        <li><a  href="{% url 'users:profile' %}">Profile</a></li>
        {%else%}
        <li><a  href="{% url 'users:login' %}">Log In</a></li>
        <li><a  href="{% url 'users:register' %}">Register</a></li>
        {% endif %}
</div>
 <h1>
     {{ menu.name }}
     {{ menu.period }}
 </h1>

    <ul>
    {% for dish in menu.dish.all %}
         <li>{{ dish.name }}</li>
             {{ dish.description }}
             {{ dish.price }}
             {{ dish.type }}
    {% endfor %}
    </ul>

restauracja/menu/templates/menu/index.html
{% block content %}
    {%if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>>
        {% endfor %}
    {% endif %}
    <div class="navbar-nav">
        {% if user.is_authenticated %}
        <li> <a  href="{% url 'users:logout' %}">Log out</a></li>
        <li><a  href="{% url 'users:profile' %}">Profile</a></li>

        {%else%}
        <li><a  href="{% url 'users:login' %}">Log In</a></li>
        <li><a  href="{% url 'users:register' %}">Register</a></li>

        {% endif %}
    </div>

    <{% if place_list %}
    <ul>
    {% for place in place_list %}
        <li><a href="{% url 'menu:detail' place.id %}">{{ place.town}}</a></li>
    {% endfor %}
    </ul>
    {% else %}
    <p>No place are available. We are in the process of develop.</p>
    {% endif %}

{% endblock content %}

restauracja/users/templates/users/login.html
{% load crispy_forms_tags %}
{% block content %}
    <div class = "content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class = "border-bottom mb-4">Log in</legend>
                 {{ form|crispy }}
            </fieldset>
            <div class = "form-group">
                <button class = "btn btn-outline-info" type="submit">Log in</button>
            </div>
        </form>
        <div class = "border - top pt-3">
            <small class = "text-muted">
                Need An Account <a class="ml-2" href = "{% url 'users:register' %}">Register</a>
            </small>
        </div>
    </div>
{% endblock content %}

restauracja/users/templates/users/logout.html
{% block content %}
    <h2>You have been logged out</h2>
    <div class = "border - top pt-3">
        <small class = "text-muted">
            <a  href = "{% url 'users:login' %}">Log In Again</a>
        </small>
    </div>

    <div class = "border - top pt-4">
        <small class = "text-muted">
            <a  href = "{% url 'menu:places' %}">Go to main site</a>
        </small>
    </div>

{% endblock content %}

restauracja/users/templates/users/profile.html
{% load crispy_forms_tags %}
{% block content %}
<div class="navbar-nav">
        <li> <a  href="{% url 'users:logout' %}">Log out</a></li>
        <li><a  href="{% url 'menu:places' %}">Main site</a></li>
</div>
    <div class="content-section">
      <div class="media">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
      <form method="POST" >
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Profile Change</legend>
              {{ u_form|crispy }}
          </fieldset>
          <div class="form-group">
              <button class="btn btn-outline-info" type="submit">Update</button>
          </div>
      </form>
    </div>
{% endblock content %}

restauracja/users/templates/users/register.html
{% load crispy_forms_tags %}
{% block content %}
    <div class = "content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class = "border-bottom mb-4">Join Today</legend>
                 {{ form|crispy }}
            </fieldset>
            <div class = "form-group">
                <button class = "btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class = "border - top pt-3">
            <small class = "text-muted">
                Already Have An Account? <a class="ml-2" href = "#">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}